Setup mobile first portfolio
kene-creator/portfolio pull request #1
Opened 2022-08-17 16:35 UTC by kene-creator

# Mobile view portfolio

### Steps covered

- Created landing page header
- Add added linters

2022-08-17 16:39 UTC, Ismailco commented
@kene-creator, you have some linter errors make sure you fix them ASAP

2022-08-17 16:52 UTC, Ismailco reviewed
Hi @kene-creator, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-17 20:30 UTC, frank1738 requested changes
Hi @kene-creator 😃 , Im [frank](@frank1738) your Code Reviewer

Good job correcting linter errors as requested by the previous reviewer
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/aphEKBb6whaA7P5pKZ/giphy.gif)

## Highlights
- Have used the right GitHub flow ✅
- Linter checks passed ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 20:30 UTC, frank1738 commented on README copy.md
> +
- [ ] Because you have not deployed the project yet, You can remove the live demo link

2022-08-17 20:30 UTC, frank1738 commented on README copy.md
> +- LinkedIn: [Kenechuwku Agagwu](https://linkedin.com/in/kenechukwuagagwu)
- [ ] Your LinkedIn link is not working, would you please remove it if it is not available

2022-08-18 11:02 UTC, ichala requested changes
Hi @kene-creator , 

Good job so far! 👏👏👏
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No Linters Errors ✔️
- Good commit messages ✔️
- PR has a good title and summary ✔️

 ## Required Changes ♻️
 
- [ ]  _**_Check The Comments Below_**_

## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 11:54 UTC, kene-creator commented on style.css
> +}
I was still working on the section. Currently I'm working on sections and I'll implement that

2022-08-18 12:07 UTC, kene-creator commented on index.html
> +      </nav>
They are no extra sections in the header

2022-08-18 12:17 UTC, omarsalem7 approved these changes
Hi @kene-creator 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 17:42 UTC, merged