Work section
kene-creator/portfolio pull request #3
Opened 2022-08-18 18:45 UTC by kene-creator

**Steps Covered**

- Built work section with HTML and CSS
-Used grid and flexbox layout

2022-08-18 19:45 UTC, Kamba56 requested changes
Hi @kene-creator, 

Good job so far!
You have done a great job building this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Linters set up correctly
- [ ] All linters checks passed
- [ ] Professional Readme file
- [ ] Correct use of GitHub flow

## Required Changes ♻️
_Please check the comments under the review for suggested changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 19:45 UTC, Kamba56 commented on style.css
>  }
- [ ] Kindly use the same fonts as the design, please. Poppins was the `font-family` used in the Figma design. You can get the font from [google fonts](https://fonts.google.com/specimen/Poppins?query=popp) and link it to your document.

2022-08-18 19:45 UTC, Kamba56 commented on index.html
> +        <a href="#" class="section-about-link"
- [ ] Please note that the languages, frameworks, and skills categories should be `<li>` elements in a `<ul>` as demanded by the [project requirements.](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#project--requirements)

2022-08-18 21:10 UTC, kene-creator commented on index.html
> +        <a href="#" class="section-about-link"
Yes I used the <ul> and <li> tag where required. Please can you point me exactly to where I didnt use it.

2022-08-18 22:36 UTC, Kamba56 commented on index.html
> +        <a href="#" class="section-about-link"
Hello @kene-creator. Your categories are supposed to be list items instead of `<div>`. That means your work should be something like this `<ul>
  <li> <h3>Languages</h3>
         <ul>...</ul>
  </li>
  <li>Frameworks</li>
  <li>Skills</li>
</ul>`

2022-08-19 07:51 UTC, kene-creator commented on index.html
> +        <a href="#" class="section-about-link"
Sorry I meant i use the ul tag and li tag where i was supposed to use it

2022-08-19 07:56 UTC, kene-creator commented on style.css
>  }
I don't know how your system works but in mine, the logo font matches the one on Figma.

2022-08-19 08:58 UTC, Kamba56 commented on style.css
>  }
Sorry about that then. It could be a problem from my browser. Kindly ask for a re-review. Thank you.

2022-08-19 08:59 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @kene-creator ✋

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-19 08:59 UTC, Kamba56 commented on index.html
> +        <a href="#" class="section-about-link"
Can I call you on zoom to show you what I mean. I can't find you on slack.

2022-08-19 09:44 UTC, merged